name: Update README Stats

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Stats
        run: |
          # Update GitHub stats in README
          curl -s "https://github-readme-stats.vercel.app/api?username=adam-paterson&show_icons=true&theme=radical&include_all_commits=true&count_private=true" > /tmp/github-stats.svg
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=adam-paterson&layout=compact&theme=radical&langs_count=8" > /tmp/top-langs.svg
          curl -s "https://github-readme-streak-stats.herokuapp.com/?user=adam-paterson&theme=radical&hide_border=true" > /tmp/streak-stats.svg
          curl -s "https://github-profile-trophy.vercel.app/?username=adam-paterson&theme=radical&no-frame=true&no-bg=true&margin-w=4" > /tmp/trophies.svg
          curl -s "https://github-readme-activity-graph.vercel.app/graph?username=adam-paterson&theme=radical" > /tmp/activity-graph.svg

          # Note: This is a simplified approach. In practice, you might need a more sophisticated script
          # to replace the URLs in the README with fresh ones or use a dedicated action.

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update GitHub stats in README" || echo "No changes to commit"
          git push